# Generated by Django 5.0.4 on 2024-06-05 23:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pais',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
