# Generated by Django 5.0.4 on 2024-06-06 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubricaEstado', '0002_alter_rubricaestado_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubricaestado',
            name='tipoRubrica',
            field=models.CharField(choices=[('FUNCIONAMENTO', 'Funcionamento'), ('INVESTIMENTO', 'Investimento')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
